title: Uprooted
subtitle: The New Haven Time Capsule Project 
author:
  name: Wax user
  email: your-email@domain.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefore some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  uprooted: # name of collection
    output: true # makes sure pages are output as html files
    layout: "uprooted_item" # the layout for the pages to use
    metadata:
      source: "uprooted.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/uprooted" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      uprooted:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - institution
          - type
          - museum_dating
          - country_provenance

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "About"
    sub:
      - label: "About"
        link: "/about"
      - label: "Credits"
        link: "/credits"  
  - label: "Stories"
    sub:
      - label: "New Haven in 1909"
        link: "/stories/1909/"
      - label: "From Beyond the Grave in 2012"
        link: "/stories/2012/"
      - label: "From the Ground to the Cloud in 2022"
        link: "/stories/2022/"
    link: "/stories/"
  - label: "Collection"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
